#!/usr/bin/env bash
#
# 维护者发布工具：将当前仓库导出为一份不含 Git 历史与本机元数据的干净
# 开源快照，并执行多重安全校验（清单比对、扩展属性检查、.git 残留检查、
# 全新仓库暂存校验）。普通部署者与贡献者无需运行本脚本。
#
# 平台要求：仅支持 macOS —— 依赖 bsdtar（--no-fflags、--no-mac-metadata
# 为 bsdtar 专有参数，GNU tar 无法运行）与 xattr 命令。
#
# 用法：scripts/export-open-source-snapshot.sh <仓库外的空目录>

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd -- "${script_dir}/.." && pwd)"
destination="${1:-}"

if [[ -z "${destination}" ]]; then
  echo "Usage: $0 /absolute/or/relative/empty-destination" >&2
  exit 64
fi

if [[ "${destination}" != /* ]]; then
  destination="${repo_root}/${destination}"
fi

destination_parent="$(dirname -- "${destination}")"
destination_name="$(basename -- "${destination}")"
if [[ ! -d "${destination_parent}" ]]; then
  echo "Destination parent must already exist: ${destination_parent}" >&2
  exit 73
fi
destination="$(cd -- "${destination_parent}" && pwd -P)/${destination_name}"

case "${destination}" in
  "${repo_root}"|"${repo_root}/"*)
    echo "Destination must be outside the current repository." >&2
    exit 64
    ;;
esac

if [[ -e "${destination}" ]]; then
  if [[ ! -d "${destination}" ]] || [[ -n "$(find "${destination}" -mindepth 1 -maxdepth 1 -print -quit)" ]]; then
    echo "Destination must not exist or must be an empty directory: ${destination}" >&2
    exit 73
  fi
else
  mkdir -p -- "${destination}"
fi

manifest="$(mktemp)"
expected_manifest="$(mktemp)"
actual_manifest="$(mktemp)"
staged_manifest="$(mktemp)"
temporary_git_dir="$(mktemp -d)"
cleanup() {
  rm -f -- "${manifest}" "${expected_manifest}" "${actual_manifest}" "${staged_manifest}"
  rm -rf -- "${temporary_git_dir}"
}
trap cleanup EXIT

cd -- "${repo_root}"

# Include the current filesystem state of tracked files and non-ignored
# untracked files. Deleted tracked files are skipped. Git history, ignored
# secrets, local uploads, dependencies, logs and build output are excluded.
while IFS= read -r -d '' path; do
  if [[ -e "${path}" || -L "${path}" ]]; then
    printf '%s\0' "${path}" >> "${manifest}"
  fi
done < <(git ls-files --cached --others --exclude-standard -z)

archive_flags=(--no-xattrs --no-acls --no-fflags --no-mac-metadata)
tar "${archive_flags[@]}" --null --files-from="${manifest}" --no-recursion -cf - \
  | tar "${archive_flags[@]}" -xf - -C "${destination}"

# Require the exported path set to match the source manifest exactly. This also
# catches files that a nested ignore rule would silently omit from a fresh Git
# repository.
LC_ALL=C sort -z "${manifest}" > "${expected_manifest}"
while IFS= read -r -d '' exported_path; do
  printf '%s\0' "${exported_path#./}" >> "${actual_manifest}"
done < <(cd -- "${destination}" && find . \( -type f -o -type l \) -print0)
LC_ALL=C sort -z -o "${actual_manifest}" "${actual_manifest}"
if ! cmp -s "${expected_manifest}" "${actual_manifest}"; then
  echo "Safety check failed: exported file manifest differs from source" >&2
  exit 70
fi

# macOS may attach an immutable com.apple.provenance marker to every newly
# created file even when metadata copying is disabled. It is generated by the
# local filesystem and is not stored by Git or by the tar stream above. Reject
# every other extended attribute, especially download, quarantine and ACL data.
if command -v xattr >/dev/null 2>&1; then
  xattr -cr "${destination}" 2>/dev/null || true
  remaining_xattrs="$({ xattr -r "${destination}" 2>/dev/null || true; } | \
    sed -n 's/^.*: \([^:]*\)$/\1/p' | sort -u)"
  unexpected_xattrs="$(printf '%s\n' "${remaining_xattrs}" | grep -v -E '^$|^com\.apple\.provenance$' || true)"
  if [[ -n "${unexpected_xattrs}" ]]; then
    echo "Safety check failed: exported snapshot contains unexpected extended attributes" >&2
    exit 70
  fi
fi

if [[ -n "$(find "${destination}" -name .git -print -quit)" ]]; then
  echo "Safety check failed: exported snapshot contains Git metadata" >&2
  exit 70
fi

# Verify that a fresh repository would stage every exported file. Keep its Git
# directory outside the snapshot so the destination remains history-free.
git init -q --bare "${temporary_git_dir}"
git --git-dir="${temporary_git_dir}" config core.bare false
GIT_DIR="${temporary_git_dir}" GIT_WORK_TREE="${destination}" git add --all
GIT_DIR="${temporary_git_dir}" GIT_WORK_TREE="${destination}" git ls-files -z \
  | LC_ALL=C sort -z > "${staged_manifest}"
if ! cmp -s "${expected_manifest}" "${staged_manifest}"; then
  echo "Safety check failed: a fresh Git repository would not stage every exported file" >&2
  exit 70
fi

echo "Open-source snapshot exported to: ${destination}"
if [[ "${remaining_xattrs:-}" == "com.apple.provenance" ]]; then
  echo "Note: macOS attached filesystem-only com.apple.provenance; Git and the tar stream do not carry it."
fi
echo "Review it, then run: git init -b main"
