/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./../components/Auth/index.vue')['default']
    AuthAll: typeof import('./../components/AuthAll/index.vue')['default']
    FileUpload: typeof import('./../components/FileUpload/index.vue')['default']
    FixedActionBar: typeof import('./../components/FixedActionBar/index.vue')['default']
    HButton: typeof import('./../layouts/ui-kit/HButton.vue')['default']
    HCheckList: typeof import('./../layouts/ui-kit/HCheckList.vue')['default']
    HDialog: typeof import('./../layouts/ui-kit/HDialog.vue')['default']
    HDropdown: typeof import('./../layouts/ui-kit/HDropdown.vue')['default']
    HDropdownMenu: typeof import('./../layouts/ui-kit/HDropdownMenu.vue')['default']
    HInput: typeof import('./../layouts/ui-kit/HInput.vue')['default']
    HKbd: typeof import('./../layouts/ui-kit/HKbd.vue')['default']
    HSelect: typeof import('./../layouts/ui-kit/HSelect.vue')['default']
    HSlideover: typeof import('./../layouts/ui-kit/HSlideover.vue')['default']
    HTabList: typeof import('./../layouts/ui-kit/HTabList.vue')['default']
    HToggle: typeof import('./../layouts/ui-kit/HToggle.vue')['default']
    HTooltip: typeof import('./../layouts/ui-kit/HTooltip.vue')['default']
    IconifyIcon: typeof import('./../components/IconifyIcon/index.vue')['default']
    ImagePreview: typeof import('./../components/ImagePreview/index.vue')['default']
    ImagesUpload: typeof import('./../components/ImagesUpload/index.vue')['default']
    ImageUpload: typeof import('./../components/ImageUpload/index.vue')['default']
    NotAllowed: typeof import('./../components/NotAllowed/index.vue')['default']
    PageHeader: typeof import('./../components/PageHeader/index.vue')['default']
    PageMain: typeof import('./../components/PageMain/index.vue')['default']
    PromptTemplateEditor: typeof import('./../components/PromptTemplateEditor/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../components/SearchBar/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    SystemInfo: typeof import('./../components/SystemInfo/index.vue')['default']
    Trend: typeof import('./../components/Trend/index.vue')['default']
  }
}

// For TSX support
declare global {
  const Auth: typeof import('./../components/Auth/index.vue')['default']
  const AuthAll: typeof import('./../components/AuthAll/index.vue')['default']
  const FileUpload: typeof import('./../components/FileUpload/index.vue')['default']
  const FixedActionBar: typeof import('./../components/FixedActionBar/index.vue')['default']
  const HButton: typeof import('./../layouts/ui-kit/HButton.vue')['default']
  const HCheckList: typeof import('./../layouts/ui-kit/HCheckList.vue')['default']
  const HDialog: typeof import('./../layouts/ui-kit/HDialog.vue')['default']
  const HDropdown: typeof import('./../layouts/ui-kit/HDropdown.vue')['default']
  const HDropdownMenu: typeof import('./../layouts/ui-kit/HDropdownMenu.vue')['default']
  const HInput: typeof import('./../layouts/ui-kit/HInput.vue')['default']
  const HKbd: typeof import('./../layouts/ui-kit/HKbd.vue')['default']
  const HSelect: typeof import('./../layouts/ui-kit/HSelect.vue')['default']
  const HSlideover: typeof import('./../layouts/ui-kit/HSlideover.vue')['default']
  const HTabList: typeof import('./../layouts/ui-kit/HTabList.vue')['default']
  const HToggle: typeof import('./../layouts/ui-kit/HToggle.vue')['default']
  const HTooltip: typeof import('./../layouts/ui-kit/HTooltip.vue')['default']
  const IconifyIcon: typeof import('./../components/IconifyIcon/index.vue')['default']
  const ImagePreview: typeof import('./../components/ImagePreview/index.vue')['default']
  const ImagesUpload: typeof import('./../components/ImagesUpload/index.vue')['default']
  const ImageUpload: typeof import('./../components/ImageUpload/index.vue')['default']
  const NotAllowed: typeof import('./../components/NotAllowed/index.vue')['default']
  const PageHeader: typeof import('./../components/PageHeader/index.vue')['default']
  const PageMain: typeof import('./../components/PageMain/index.vue')['default']
  const PromptTemplateEditor: typeof import('./../components/PromptTemplateEditor/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SearchBar: typeof import('./../components/SearchBar/index.vue')['default']
  const SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
  const SystemInfo: typeof import('./../components/SystemInfo/index.vue')['default']
  const Trend: typeof import('./../components/Trend/index.vue')['default']
}